apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      run: portfolio
  template:
    metadata:
      labels:
        run: portfolio
    spec:
      containers:
      - name: portfolio
        image: nginx
        ports:
          - containerPort: 3000
