stages: 

  - build_frontend 

before_script: 
  - sudo yum install epel-release -y

  - sudo yum install python3-pip -y

  - sudo python3 -m pip install pip --upgrade 

  - sudo pip install awscli

  - sudo pip3 install ansible

  - sudo yum install nodejs -y

build_frontend: 

  stage: build_frontend 

  script: 

    - cd frontend

    - sudo npm install

    - sudo npm install react-scripts -f

    - sudo npm run build 

  artifacts: 

    paths: 

      - frontend/
